Spark ttfb poc
filecoin-station/spark-evaluate pull request #434
Opened 2024-12-23 13:17 UTC by pyropy

2024-12-29 12:38 UTC, juliangruber commented
Quoting @pyropy:

> I left them (the PRs) as draft as I am unsure if there is a way to reference spark-evaluate commit from spark-stats and I am not sure if we should have another section for ttfb on dashboard

2025-01-05 21:49 UTC, juliangruber requested changes

2025-01-05 21:49 UTC, juliangruber commented on lib/committee.js
> +    assert.strictEqual(m.roundId, this.retrievalTask.roundId, 'roundId must match')
why was this added?

2025-01-05 21:49 UTC, juliangruber commented on lib/preprocess.js
> +   * @param {Partial<import('./round.js').RoundData>} r
Since we're already passing `round.pointerize` as the last argument, I suggest we also pass `round.index` instead of `round`, for consistency and to prevent redundancy

2025-01-05 21:49 UTC, juliangruber commented on lib/public-stats.js
> +const updateRetreivalTimes = async (pgClient, committees) => {
```suggestion
const updateRetreivalTimings = async (pgClient, committees) => {
```

2025-01-05 21:49 UTC, juliangruber commented on lib/public-stats.js
> +    INSERT INTO retrieval_times
```suggestion
    INSERT INTO retrieval_timings
```

2025-01-05 21:49 UTC, juliangruber commented on lib/public-stats.js
> +  // conflic should never happen, but in case it does we'll ignore the new value
If conflicts shouldn't happen, I suggest we remove the conflict handling and let it fail. If everything is right, it will never fail. If it fails, it will inform us of a bug to fix.

2025-01-05 21:50 UTC, juliangruber commented
> Quoting @pyropy:
> 
> > I left them (the PRs) as draft as I am unsure if there is a way to reference spark-evaluate commit from spark-stats and I am not sure if we should have another section for ttfb on dashboard

I'm marking this as ready for review as the open questions don't affect this PR and I think it can be merged as soon as reviews pass

2025-01-07 06:51 UTC, pyropy commented on lib/committee.js
> +    assert.strictEqual(m.roundId, this.retrievalTask.roundId, 'roundId must match')
I have changed task id structure from `cid::minerId` to `cid::minerId::roundId` hence we're checking round id here.

2025-01-07 21:57 UTC, juliangruber commented on lib/committee.js
> +    assert.strictEqual(m.roundId, this.retrievalTask.roundId, 'roundId must match')
I understand, but what is the motivation?

2025-01-09 07:39 UTC, bajtos requested changes

2025-01-09 07:39 UTC, bajtos commented on lib/public-stats.js
> +const updateRetreivalTimings = async (pgClient, committees) => {
Typo.

```suggestion
const updateRetrievalTimings = async (pgClient, committees) => {
```

2025-01-09 07:39 UTC, bajtos commented on lib/public-stats.js
> +    ON CONFLICT(day, miner_id, task_id) DO NOTHING
I have mixed feelings about this design.

- Task id was designed to distinguish tasks within one round. spark-evaluate always looks at one round only.
- Since it's only `updateRetreivalTimings()` that needs to handle the case when one task is performed more than once during a day, I prefer to implement a solution that's limited to `updateRetreivalTimings()` only. For example, we can forward the current round number through `updatePublicStats()` to `updateRetreivalTimings()` and then combine old-style taskId with the round number.
- Because task_id includes a round number, it does not help us detect cases when the same content was tested twice on the same day, it only ensures we can record timings for each task occurrence.

I propose a different DB schema for consideration: Instead of having one row per day+task+round, have only one row per day and store the p50 values in an array.

Something along the following lines:

```sql
INSERT INTO retrieval_timings
(day, miner_id, time_to_first_byte_p50) VALUES 
(now(), unnest($2::text[]), unnest($3::int[]))
ON CONFLICT(day, miner_id) 
DO UPDATE SET
  time_to_first_byte_p50 = array_cat(
    retrieval_timings.time_to_first_byte_p50,
    EXCLUDED.time_to_first_byte_p50
  )
```

2025-01-09 07:39 UTC, bajtos commented on migrations/021.do.add-retrieval-times.sql
> +  time_to_first_byte_p50 INT NOT NULL,
This column name is rather long, how about using the abbreviation TTFB?

```suggestion
  ttfb_p50 INT NOT NULL,
```

2025-01-09 07:39 UTC, bajtos commented on test/public-stats.test.js
> +  function givenTimeToFirstByte (measurment, timeToFirstByte) {
Typo

```suggestion
  function givenTimeToFirstByte (measurement, timeToFirstByte) {
```

2025-01-13 07:15 UTC, pyropy commented on lib/public-stats.js
> +    ON CONFLICT(day, miner_id, task_id) DO NOTHING
Nice idea, let's go with the array for the value field.

2025-01-13 07:22 UTC, pyropy commented on lib/committee.js
> +    assert.strictEqual(m.roundId, this.retrievalTask.roundId, 'roundId must match')
Motivation behind adding the `roundId` to `taskId` was to avoid conflicts when updating `retrieval_timings` values as pkey for the value was day, taskId and minerId. If we'd kept old `taskId` in that structure we would encounter conflicts whenever we'd measure same CID for same storage provider twice in a day. 

I am going to switch table to use int array for storing p50 values for all measurements for a single storage provider and rollback changes I've done around new `taskId`.

2025-01-13 12:59 UTC, pyropy commented on lib/public-stats.js
> +    JSON.stringify(rows)
I have done this as I am unable to `unnest` nested array (`unnest` would convert nested array to int values). If you have some suggestions on how to do this in a cleaner way I'd appreciate that 🙏🏻

2025-01-13 14:56 UTC, bajtos approved these changes
Almost there! 💪🏻

2025-01-13 14:58 UTC, bajtos requested changes
Ouch, I meant to request changes.

2025-01-13 15:44 UTC, pyropy commented on lib/public-stats.js
> +      ttfbMeasurments.push(m.first_byte_at - m.start_at)
Nice catch, I'm going to add test for this also.

2025-01-13 16:06 UTC, bajtos commented on lib/public-stats.js
> +      ttfbMeasurments.push(m.first_byte_at - m.start_at)
Please also add a check that `m.first_byte_at - m.start_at` is not `NaN`. That should hopefully cover the remaining edge cases.

```
❯ node
Welcome to Node.js v22.13.0.
Type ".help" for more information.
> 'a' - 12
NaN
```

2025-01-13 18:31 UTC, pyropy commented on lib/public-stats.js
> +    JSON.stringify(rows)
I've tried removing `JSON.stringify` but it throws following error `error: invalid input syntax for type json`. I think node-postgres handles serialization but only to postgres binary format, so we need to serialize it to json first before it get's converted to binary.

2025-01-13 18:42 UTC, pyropy commented on lib/public-stats.js
> +      ttfbMeasurments.push(m.first_byte_at - m.start_at)
I have added checks and test to cover edge cases.

2025-01-14 10:12 UTC, bajtos approved these changes
LGTM 👏🏻

2025-01-14 10:12 UTC, bajtos commented on test/public-stats.test.js
> +        { ...VALID_MEASUREMENT, cid: 'cidone', minerId: 'f1second', retrievalResult: 'OK', first_byte_at: 'invalid' }
Nitpick - this may be safer as it disables the type check only for one property value, not the entire line.

```suggestion
        // @ts-ignore
        { ...VALID_MEASUREMENT, cid: 'cidone', minerId: 'f1second', retrievalResult: 'OK', first_byte_at: /** @type {any} */('invalid') }
```

2025-01-14 10:45 UTC, merged